### ISSUE TITLE
Bail amount should be missing, when bail_type = denied

### ISSUE THREAD

**Issue by itsamejoshab** [CodeForPhilly/pbf-analysis#1]
I'd like to request we modify the code that generates the .csv data to show a missing value for bail_amount whenever the bail_type is 'Denied'. It currently shows a 0, which could possibly lead to analysts making mistakes with averaging and other aggregates if they are not careful. I figure its easier to just create missing values in the data engineering scripts rather than warn everybody.

**Comment by notchia** [comment]
No longer relevant
