### ISSUE TITLE
[dashboard] 3. Which neighborhoods are heavily impacted by the bail system?

### ISSUE THREAD

**Issue by irishryoon** [CodeForPhilly/pbf-analysis#12]

**Comment by douglaswlee** [comment]
I would also be interested in contributing here

**Comment by irishryoon** [comment]
@douglaswlee  I created a few visualizations using tableau. They are included in the dashboard.ipynb section 3. Feel free to enhance those and/or create new visualizations!

**Comment by notchia** [comment]
This has been addressed in the first dashboard iteration.
